export const myPaintings = [
	"Alienation_No.12.jpg",
	"Alienation_No.13.jpg",
	"Alienation_No.2.jpg",
	"Alienation_No.1.jpg",  
	"Alienation_No.3.jpg",
  "Alienation_No.4.jpg",
	"Alienation_No.6.jpg",
	"Alienation_No.5.jpg",
	"Alienation_No.31.jpg",
	"Alienation_No.9.jpg",
	"Alienation_No.15.jpg",
	"Alienation_No.11.jpg",
 	"Alienation_No.10.jpg",
	"Alienation_No.16.jpg",
	"Alienation_No.17.jpg",
 	"Alienation_No.20.jpg",
	"Alienation_No.21.jpg",
	"Alienation_No.22.jpg",
	"Alienation_No.23.jpg",
	"Alienation_No.24.jpg",
 	"Alienation_No.26.jpg",
	"Alienation_No.30.jpg",	
	"Alienation_No.7.jpg",

	"Alienation_No.33.jpg",
	"Alienation_No.34.jpg",
	"chinesebed.jpg",
	"Firework_No.1.jpg",
	"Firework_No.2.jpg",
	"Firework_No.3.jpg",
	"Firework_No.4.jpg",
	"thebiggestblue.jpg",
	"smoke.jpg",
	"purple.jpg",
	"sick.jpg",
	"smalldream.jpg",
	"theharderyoufall.jpg",
	"tunnel.jpg",

	"bigdream.jpg",
 	"black.jpg",
	"chandeliers.jpg",

	"whitebed.jpg",
	"parked.jpg",
	// "detail1.png",
	// "detail2.png",
	// "detail3.png",
	// "detail4.png",
	// "detail5.png",
	// "detail6.png",
	// "detail7.png",
	// "detail8.png",
	// "detail9.png",
	// "detail11.png",


	"pink.jpg",
	"light.jpg",
	// "openning.jpg",

	"face.jpg",
	"wishyouwerehere.jpg",
	"crack.jpg",
	"beard.jpg",
	"eye.jpg",

	"head.jpg",
];
